import numpy as np
from models.model import Model
from keras import Sequential, layers, models
from keras.layers import Rescaling
from keras.optimizers import RMSprop, Adam
from config import pretrained_model_path

class RandomModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # very similar to transfered_model.py, the only difference is that you should randomize the weights
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # randomize the weights of the loaded model, possibly by using _randomize_layers
        # use this model by removing the last layer, adding dense layers and an output layer
        pretrained = models.load_model(pretrained_model_path)

        # remove final layer
        base_model = models.Model(
            inputs=pretrained.inputs,
            outputs=pretrained.layers[-2].output
        )

        # randomize all weights
        self._randomize_layers(base_model)

        # add new classifier head (same as transfer model)
        x = base_model.output
        x = layers.Dense(24, activation="relu", name="random_dense_1")(x)
        x = layers.Dense(24, activation="relu", name="random_dense_2")(x)
        output = layers.Dense(categories_count, activation="softmax", name="random_output")(x)

        self.model = models.Model(inputs=base_model.input, outputs=output)
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=RMSprop(learning_rate=0.001),
            loss="categorical_crossentropy",
            metrics=["accuracy"],
        )

    @staticmethod
    def _randomize_layers(model):
        # Your code goes here

        # you can write a function here to set the weights to a random value
        # use this function in _define_model to randomize the weights of your loaded model
        for layer in model.layers:
            weights = layer.get_weights()

            if weights:  # only layers with weights
                new_weights = [
                    np.random.normal(size=w.shape).astype(w.dtype)
                    for w in weights
                ]
                layer.set_weights(new_weights)
