from models.model import Model
from keras import Sequential, layers, models
from keras.layers import Rescaling
from keras.optimizers import RMSprop, Adam
from config import pretrained_model_path

class TransferedModel(Model): 
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # use this model by removing the last layer, adding dense layers and an output layer
        
        # load your trained facial recognition model
        pretrained = models.load_model(pretrained_model_path)

        # eliminate the final softmax layer (which specializes it to a 3-class problem)
        base_model = models.Model(
            inputs=pretrained.inputs,
            outputs=pretrained.layers[-2].output
        )
        # freeze all parameters in the remainder so that they cannot change through further learning
        for layer in base_model.layers:
            layer.trainable = False

        # bolt on one or more fully connected layers to perform an arbitrary computation over the features inferred by your facial recognition model
        x = base_model.output
        x = layers.Dense(64, activation="relu", name="transfer_dense_1")(x)
        x = layers.Dense(48, activation="relu", name="transfer_dense_2")(x)

        output = layers.Dense(categories_count, activation="softmax", name="transfer_output")(x)
        self.model = models.Model(inputs=base_model.inputs, outputs=output)

    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=RMSprop(learning_rate=0.001),
            loss="categorical_crossentropy",
            metrics=["accuracy"],
        )
